import Head from 'next/head'
import Welcome from '../components/UI/organisms/Welcome/Welcome'

 const Home = () => {
  return (
   <>
      <Head>
        <title>Articles App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome></Welcome>
      </>
  )
}
export default Home ;
