import Head from "next/head";
import Welcome from "../components/UI/organisms/Welcome/Welcome";

export function getStaticProps({locale}) {
  return {
    props: {
      locale,
    },
  };
}

const Home = (props) => {
  return (
    <>
      <Head>
        <title>Articles App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{props.locale}</h1>
      <Welcome></Welcome>
    </>
  );
};
export default Home;
