const actions = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  CLEAR_LOGIN: "CLEAR_LOGIN",
  LOGOUT: "LOGOUT",
  ARTICLES: "ARTICLES",
  ARTICLES_SUCCESS: "ARTICLES_SUCCESS",
  ARTICLES_FAILED : "ARTICLES_FAILED",
  SEARCH_ARTICLES : "SEARCH_ARTICLES",
};
export default actions;
